version: "3"

services:
  app:
    build: .
    container_name: go_app_banco_de_dados
    ports:
      - "9000:9000"
    volumes:
      - .:/go/src/

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306