version: "3"

services:
    app:
        build: .
        container_name: go-socket
        ports:
            - "9000:9000"
        volumes:
            - .:/go/src/
        networks:
            - app-network

    db:
        image: postgres:15-alpine
        container_name: db-postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: postgres
            POSTGRES_DB: go-socket-db
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
